#! /bin/sh

bspc config border_width        0
bspc config window_gap		0 
bspc config focus_follows_pointer true

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d dev web media IV V VI VII VIII IX X

bspc rule -a Chromium desktop=^2
bspc rule -a Google-chrome-stable desktop=^2
bspc rule -a Firefox desktop=^2
bspc rule -a Opera desktop=^2
bspc rule -a vlc desktop=^3

panel &
